"""
analyse_video.py

Facial motion + optional metric depth pipeline.

Before the first run (already shipped in this repo):
    python -c "from utils.fps_points import build_and_save_point_index; build_and_save_point_index()"

Usage:
    python analyse_video.py -f path/to/image_directory --onnx
    python analyse_video.py -f path/to/image_directory --onnx --detector scrfd
    python analyse_video.py -f path/to/image_directory --onnx --with_depth

Outputs (written into the image directory):
    landmarks.csv, pose.csv, region CSVs, and optionally landmarks_depth.csv
"""

import argparse
import os
import csv
import cv2
import numpy as np
import yaml

import torch
from unidepth.models import UniDepthV2
from unidepth.utils.camera import Pinhole

from FaceBoxes import FaceBoxes
from TDDFA import TDDFA
from TDDFA_ONNX import TDDFA_ONNX
from utils.region_motion import process_video_landmarks
from utils.pose import calc_pose
from utils.fps_points import load_point_index


# ---------------------------------------------------------------------------
# InsightFace / SCRFD wrapper (unchanged from previous version)
# ---------------------------------------------------------------------------

def load_scrfd():
    try:
        from insightface.app import FaceAnalysis
    except ImportError:
        raise ImportError(
            "InsightFace is not installed.\n"
            "Run:  pip install insightface onnxruntime"
        )
    app = FaceAnalysis(
        name="buffalo_sc",
        allowed_modules=["detection"],
        providers=["CPUExecutionProvider"],
    )
    app.prepare(ctx_id=-1, det_size=(640, 640))
    return app


def scrfd_detect(app, frame):
    faces = app.get(frame)
    if not faces:
        return []
    boxes = []
    for face in faces:
        x1, y1, x2, y2 = face.bbox.astype(np.float32)
        conf = float(face.det_score)
        boxes.append(np.array([x1, y1, x2, y2, conf], dtype=np.float32))
    return boxes


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(description="Per-region facial motion analyser")
    parser.add_argument("-c", "--config",   type=str, default="configs/mb1_120x120.yml")
    parser.add_argument("-f", "--input",    type=str, required=True,
                        help="Path to directory containing image frames")
    parser.add_argument("--fps",            type=float, default=30.0,
                        help="Frames per second (default: 30.0)")
    parser.add_argument("--onnx",           action="store_true", default=False,
                        help="Use ONNX runtime for the 3DMM regressor (recommended)")
    parser.add_argument("--detector",       type=str, default="facebox",
                        choices=["facebox", "scrfd"],
                        help="facebox (default) or scrfd (better for 4-5m footage)")
    parser.add_argument("--point_index",    type=str, default="bfm_468_indices.json",
                        help="Path to the 468-point index JSON (generated by fps_points.py)")
    parser.add_argument("--with_depth",      action="store_true", default=False,
                        help="Run UniDepth and save depth values for the 468 FPS points")
    parser.add_argument("--patch_size",      type=int, default=2,
                        help="Patch radius for median depth sampling. 2 means 5x5 patch")
    parser.add_argument("--focal_length_mm", type=float, default=26.0,
                        help="Camera focal length in mm")
    parser.add_argument("--sensor_width_mm", type=float, default=36.0,
                        help="Sensor width assumption in mm")
    parser.add_argument("--sensor_width_px", type=int, default=4032,
                        help="Sensor/reference width in pixels for focal length conversion")
    parser.add_argument("--source_width_px", type=int, default=1280,
                        help="Original video/source width before processing")
    return parser.parse_args()


# ---------------------------------------------------------------------------
# UniDepth helpers
# ---------------------------------------------------------------------------

def get_device():
    """Use Apple Silicon MPS if available, otherwise CPU."""
    return torch.device("mps" if torch.backends.mps.is_available() else "cpu")


def build_intrinsics(frame_width, frame_height, args):
    """
    Build camera intrinsics using the same scaling logic as the working
    InsightFace + UniDepth pipeline.
    """
    focal_length_px_sensor = (args.focal_length_mm * args.sensor_width_px) / args.sensor_width_mm
    scale = frame_width / args.source_width_px
    f = focal_length_px_sensor * scale
    cx = frame_width / 2
    cy = frame_height / 2
    return [
        [f, 0, cx],
        [0, f, cy],
        [0, 0, 1],
    ]


def predict_depth_map(depth_model, frame_bgr, args, device):
    """Run UniDepthV2 and return a metric depth map with shape (H, W)."""
    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    h, w = frame_bgr.shape[:2]

    intrinsics = build_intrinsics(w, h, args)
    intrinsics_tensor = torch.tensor([intrinsics], dtype=torch.float32).to(device)
    camera = Pinhole(K=intrinsics_tensor).to(device)

    image_tensor = (
        torch.from_numpy(frame_rgb)
        .permute(2, 0, 1)
        .unsqueeze(0)
        .float()
        .to(device) / 255.0
    )

    with torch.no_grad():
        predictions = depth_model.infer(image_tensor, camera=camera)

    return predictions["depth"][0, 0].cpu().numpy()


def sample_depth(depth_map, px, py, patch_size=2):
    """
    Sample a median depth value from a local patch around projected pixel (px, py).
    Returns an empty string if the point is outside the image.
    """
    h, w = depth_map.shape[:2]
    x = int(round(float(px)))
    y = int(round(float(py)))

    if not (0 <= x < w and 0 <= y < h):
        return ""

    x1 = max(x - patch_size, 0)
    x2 = min(x + patch_size + 1, w)
    y1 = max(y - patch_size, 0)
    y2 = min(y + patch_size + 1, h)

    patch = depth_map[y1:y2, x1:x2]
    if patch.size == 0:
        return ""

    return float(np.median(patch))


# ---------------------------------------------------------------------------
# CSV savers
# ---------------------------------------------------------------------------

def save_region_results(results, input_path):
    """Save one CSV per region (pos/vel/acc xyz, nose-subtracted)."""
    base = input_path.rstrip(os.sep)
    header = "frame,pos_x,pos_y,pos_z,vel_x,vel_y,vel_z,acc_x,acc_y,acc_z"
    for region_name, data in results.items():
        out_path = f"{base}_{region_name}.csv"
        n_frames = data["position"].shape[0]
        rows = []
        for i in range(n_frames):
            p = data["position"][i]
            v = data["velocity"][i]
            a = data["acceleration"][i]
            rows.append(
                f"{i},{p[0]:.4f},{p[1]:.4f},{p[2]:.4f},"
                f"{v[0]:.4f},{v[1]:.4f},{v[2]:.4f},"
                f"{a[0]:.4f},{a[1]:.4f},{a[2]:.4f}"
            )
        with open(out_path, "w") as f:
            f.write(header + "\n")
            f.write("\n".join(rows))
        print(f"  Saved: {out_path}")


def save_pose(pose_sequence, input_path):
    """Save global head pose (yaw, pitch, roll) per frame."""
    base = input_path.rstrip(os.sep)
    out_path = f"{base}_pose.csv"
    with open(out_path, "w") as f:
        f.write("frame,yaw,pitch,roll\n")
        for i, (yaw, pitch, roll) in enumerate(pose_sequence):
            f.write(f"{i},{yaw:.4f},{pitch:.4f},{roll:.4f}\n")
    print(f"  Saved: {out_path}")



def save_landmarks(landmark_sequence, input_path, n_points=468):
    """
    Save all 468 nose-subtracted point positions per frame.

    Columns: frame, pt0_x, pt0_y, pt0_z, pt1_x, pt1_y, pt1_z, ..., pt467_z
    This is the file to use when comparing point-by-point with another method.
    Point IDs match bfm_468_pointmap.json exactly.
    """
    base = input_path.rstrip(os.sep)
    out_path = f"{base}_landmarks.csv"

    # Build header: frame, pt0_x, pt0_y, pt0_z, pt1_x, ...
    coord_headers = []
    for i in range(n_points):
        coord_headers += [f"pt{i}_x", f"pt{i}_y", f"pt{i}_z"]
    header = ["frame"] + coord_headers

    with open(out_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for frame_idx, pts in enumerate(landmark_sequence):
            # pts shape: (468, 3)
            row = [frame_idx] + pts.flatten().round(4).tolist()
            writer.writerow(row)

    print(f"  Saved: {out_path}")


def save_landmarks_with_depth(landmark_sequence, pixel_sequence, depth_sequence, input_path, n_points=468):
    """
    Save 468 points per frame with:
      - nose-subtracted 3D coordinates: pt{i}_x, pt{i}_y, pt{i}_z
      - projected image pixels: pt{i}_px, pt{i}_py
      - UniDepth depth value: pt{i}_depth

    Also saves median_depth_m for each frame.
    """
    base = input_path.rstrip(os.sep)
    out_path = f"{base}_landmarks_depth.csv"

    headers = ["frame", "median_depth_m", "valid_depth_points"]
    for i in range(n_points):
        headers += [
            f"pt{i}_x", f"pt{i}_y", f"pt{i}_z",
            f"pt{i}_px", f"pt{i}_py",
            f"pt{i}_depth",
        ]

    with open(out_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(headers)

        for frame_idx, (pts_3d, pts_px, depths) in enumerate(zip(landmark_sequence, pixel_sequence, depth_sequence)):
            valid_depths = [d for d in depths if d != ""]
            median_depth = float(np.median(valid_depths)) if valid_depths else ""
            valid_count = len(valid_depths)

            row = [
                frame_idx,
                round(median_depth, 4) if median_depth != "" else "",
                valid_count,
            ]

            for point_idx in range(n_points):
                x, y, z = pts_3d[point_idx]
                px, py = pts_px[point_idx]
                d = depths[point_idx]
                row += [
                    round(float(x), 4),
                    round(float(y), 4),
                    round(float(z), 4),
                    round(float(px), 4),
                    round(float(py), 4),
                    round(float(d), 4) if d != "" else "",
                ]

            writer.writerow(row)

    print(f"  Saved: {out_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    # --- Load 3DMM config and regressor ---
    cfg = yaml.load(open(args.config), Loader=yaml.SafeLoader)
    tddfa = TDDFA_ONNX(**cfg) if args.onnx else TDDFA(**cfg)

    # --- Optional UniDepth model for 468-point depth sampling ---
    depth_model = None
    device = None
    if args.with_depth:
        print("Loading UniDepthV2 for 468-point depth sampling...")
        device = get_device()
        depth_model = UniDepthV2.from_pretrained("lpiccinelli/unidepth-v2-vitl14").to(device)
        depth_model.eval()
        print(f"  UniDepth device: {device}")

    # --- Load detector ---
    if args.detector == "scrfd":
        print("Detector: SCRFD (InsightFace)")
        scrfd_app = load_scrfd()
        def detect(frame): return scrfd_detect(scrfd_app, frame)
    else:
        print("Detector: FaceBoxes")
        fb = FaceBoxes()
        def detect(frame): return fb(frame)

    # --- Load 468-point index ---
    # Raises a clear error with instructions if the file doesn't exist yet.
    print(f"Loading point index: {args.point_index}")
    point_indices, region_map, nose_dense_idx = load_point_index(args.point_index)
    n_points = len(point_indices)
    print(f"  {n_points} points loaded")

    # --- Load PNG images ---
    if not os.path.isdir(args.input):
        raise RuntimeError(f"Directory not found: {args.input}")

    image_exts = (".png", ".jpg", ".jpeg", ".bmp", ".webp")
    image_files = sorted(
        f for f in os.listdir(args.input) if f.lower().endswith(image_exts)
    )
    if not image_files:
        raise RuntimeError(f"No image files found in: {args.input}")

    print(f"Input:  {args.input}")
    print(f"FPS:    {args.fps:.2f}  |  Frames: {len(image_files)}")

    # --- Process frames ---
    # ver_sequence_68:   (3, 68) per frame — for region kinematics
    # ver_sequence_dense: (468, 3) per frame — FPS-selected dense points
    ver_sequence_68       = []
    ver_sequence_dense    = []
    pixel_sequence_dense  = []
    depth_sequence_dense  = []
    pose_sequence         = []
    param_sequence        = []
    skipped = 0

    for frame_idx, image_file in enumerate(image_files):
        frame = cv2.imread(os.path.join(args.input, image_file))
        if frame is None:
            skipped += 1
            continue

        detected = detect(frame)
        if not detected:
            skipped += 1
            continue

        detected_box = detected[0]
        coords = detected_box[:4]
        x1, y1, x2, y2 = int(coords[0]), int(coords[1]), int(coords[2]), int(coords[3])

        if (x2 - x1) <= 0 or (y2 - y1) <= 0:
            skipped += 1
            continue

        box = np.array([x1, y1, x2, y2], dtype=np.float32)

        try:
            param_lst, roi_box_lst = tddfa(frame, [box], crop_policy="box")

            # --- 68-point sparse landmarks (for region kinematics) ---
            ver_68 = tddfa.recon_vers(param_lst, roi_box_lst, dense_flag=False)[0]
            ver_sequence_68.append(ver_68)

            # --- Dense mesh → select 468 FPS points ---
            # dense_flag=True gives shape (3, 38365)
            ver_full = tddfa.recon_vers(param_lst, roi_box_lst, dense_flag=True)[0]

            # Subtract nose position (dense mesh nose index) for relative motion
            nose_pos = ver_full[:, nose_dense_idx]             # (3,)
            ver_relative = ver_full - nose_pos[:, np.newaxis]  # (3, 38365)

            # Extract the 468 FPS-selected points, shape → (468, 3)
            pts_468_relative = ver_relative[:, point_indices].T
            ver_sequence_dense.append(pts_468_relative)

            # Projected 2D image pixels (non-nose-subtracted mesh x/y)
            pts_468_projected = ver_full[:2, point_indices].T  # (468, 2)
            pixel_sequence_dense.append(pts_468_projected)

            # Optional: sample UniDepth at each projected 2D landmark pixel
            if args.with_depth:
                depth_map = predict_depth_map(depth_model, frame, args, device)
                point_depths = []
                for px, py in pts_468_projected:
                    d = sample_depth(depth_map, px, py, patch_size=args.patch_size)
                    point_depths.append(d)
                depth_sequence_dense.append(point_depths)

            param_sequence.append(param_lst[0])

            if frame_idx % 50 == 0 or frame_idx + 1 == len(image_files):
                print(f"  Frame {frame_idx + 1}/{len(image_files)}...")

        except Exception as e:
            print(f"  Frame {frame_idx} ({image_file}) failed: {e}")
            skipped += 1

    print(f"Processed {len(ver_sequence_68)} frames, skipped {skipped}")

    if len(ver_sequence_68) < 3:
        print("Not enough frames for kinematics (need at least 3). Exiting.")
        return

    # --- Head pose ---
    print("Extracting head pose...")
    for param in param_sequence:
        _, pose = calc_pose(param)
        pose_sequence.append(pose)

    # --- Region kinematics (from 68-pt sparse landmarks, same as before) ---
    print("Computing region kinematics...")
    results = process_video_landmarks(ver_sequence_68, args.fps)

    # --- Save ---
    print("Saving CSVs...")
    save_region_results(results, args.input)
    save_pose(pose_sequence, args.input)
    save_landmarks(ver_sequence_dense, args.input, n_points=n_points)

    if args.with_depth:
        save_landmarks_with_depth(
            ver_sequence_dense,
            pixel_sequence_dense,
            depth_sequence_dense,
            args.input,
            n_points=n_points,
        )

    print("Done.")


if __name__ == "__main__":
    main()
